[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@foundry-devops=lib/foundry-devops"]
ffi = true
fs_permissions = [
  { access = "read", path = "./broadcast" }
]
